### ISSUE TITLE
Error if ~/.env file does not exist

### ISSUE THREAD

**Issue by zyndagj** [TACC-Cloud/tapis-cli-ng#225]
**Describe the bug**
All tapis commands fail if a `~/.env` file does not exist.

**To Reproduce**
1. Delete `.env` if it exists
```
$ rm -f ~/.env
```
2. Create and load fresh environment
```
$ conda create -y -n tapis-cli-ng -c defaults pip python=2.7
$ source activate tapis-cli-ng
$ pip install git+https://github.com/TACC-Cloud/tapis-cli-ng.git
```
3. Run tapis commands
```
$ tapis --help
Traceback (most recent call last):
  File "/Users/gzynda/miniconda3/envs/tapis-cli-ng/bin/tapis", line 5, in <module>
    from tapis_cli.main import main
  File "/Users/gzynda/miniconda3/envs/tapis-cli-ng/lib/python2.7/site-packages/tapis_cli/main.py", line 13, in <module>
    from . import settings
  File "/Users/gzynda/miniconda3/envs/tapis-cli-ng/lib/python2.7/site-packages/tapis_cli/settings/__init__.py", line 8, in <module>
    _ENV_PATH = load_config()  # noqa
  File "/Users/gzynda/miniconda3/envs/tapis-cli-ng/lib/python2.7/site-packages/tapis_cli/settings/config.py", line 36, in load_config
    file_name = find_config(filename='.env')
  File "/Users/gzynda/miniconda3/envs/tapis-cli-ng/lib/python2.7/site-packages/tapis_cli/settings/config.py", line 20, in find_config
    env_file = find_dotenv(filename, raise_error_if_not_found=True)
  File "/Users/gzynda/miniconda3/envs/tapis-cli-ng/lib/python2.7/site-packages/dotenv/main.py", line 269, in find_dotenv
    raise IOError('File not found')
IOError: File not found
```
4. Create `~/.env` file
```
$ touch ~/.env
```
5. Run tapis commands
```
$ tapis --help
usage: tapis [--version] [-v | -q] [--log-file LOG_FILE] [-h] [--debug]

Tapis CLI: Command line tools to support the TACC Tapis platform. For support
contact "TACC Help" <cli-help@tacc.cloud>

optional arguments:
  --version            show program's version number and exit
  -v, --verbose        Increase verbosity of output. Can be repeated.
  -q, --quiet          Suppress output except warnings and
```

**Expected behavior**
Tapis should create a `.env` file if one cannot be found on the normal search paths.

**Desktop (please complete the following information):**
 - OS: OSX 10.11.6
 - Version
```
$ tapis versions
Abaco: 1.3.0
Agave: 2.4.0-r9c8adc7
Aloe: 2.4.0-r9c8adc7
Gitlab 11.4
Keys: 1.0.1

$ pip list | grep tapis
tapis-cli                     0.3.0
```

**Comment by mwvaughn** [comment]
Thanks! Will get that fixed.
